### ISSUE TITLE
Why are transactions so expensive how to change that?

### ISSUE THREAD

**Issue by Alexander112255** [Al366io/solana-transactions-wrapper#8]
Transactions seems to be 10 times more expensive than interacting directly with raydium pool, why is that and can it be changed? I see that the library interacts with jupiter aggegator

**Comment by Al366io** [comment]
Hi, this wrapper has been built for a bot that required very fast transaction with very few possibilities in having the trans. rejected. That's why the base fee for transactions is higher. (still very low, tho.)
If you wish to lower it, you can play with the `getSwapTransaction` method, in particular with `prioritizationFeeLamports` which is now set to auto. 

If you find a good balance of not-rejected transactions and lower fees, i'll be happy to review your PR and merge your changes 😁
